In [110]:
import numpy as np

In [111]:
np.__version__

'2.3.1'

In [112]:
np.array([1,2,3]), type(np.array([1,2,3]))

(array([1, 2, 3]), numpy.ndarray)

In [113]:
np.array([1,2,3,"hello"]), type(np.array([1,2,3]))

(array(['1', '2', '3', 'hello'], dtype='<U21'), numpy.ndarray)

In [114]:
array = np.array([1,2,3])
array, array.dtype

(array([1, 2, 3]), dtype('int64'))

In [115]:
array = np.array([1,2,3], dtype = np.int8)
array, array.dtype

(array([1, 2, 3], dtype=int8), dtype('int8'))

In [116]:
array = np.array([1,2,3,127,-128], dtype = np.int8)
array, array.dtype

(array([   1,    2,    3,  127, -128], dtype=int8), dtype('int8'))

In [117]:
array = np.array([1,2,3,128, 255], dtype = np.uint8)
array, array.dtype

(array([  1,   2,   3, 128, 255], dtype=uint8), dtype('uint8'))