In [8]:
import numpy as np

In [9]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [10]:
np.array(range(7))

array([0, 1, 2, 3, 4, 5, 6])

In [11]:
np.arange(7,15)

array([ 7,  8,  9, 10, 11, 12, 13, 14])

In [12]:
np.arange(7,15,3)

array([ 7, 10, 13])