In [59]:
import numpy as np

In [60]:
array = np.array([23, 41, 500, 10, 40, 30, 310, 20, 30, 101, 203, 30])
array

array([ 23,  41, 500,  10,  40,  30, 310,  20,  30, 101, 203,  30])

In [61]:
print(array.min(), array.max(), min(array), max(array))

10 500 10 500


In [62]:
array.sum(), sum(array)

(np.int64(1338), np.int64(1338))

In [63]:
array.mean()

np.float64(111.5)

In [64]:
array = np.array([23, 41, 500, 10, 40, 30, 310, 20, 30, 101, 203, 30])
array.min(), array.argmin()

(np.int64(10), np.int64(3))

In [65]:
array.max(), array.argmax()

(np.int64(500), np.int64(2))

In [66]:
array[array>100]

array([500, 310, 101, 203])

In [67]:
array[-2:]

array([203,  30])

In [68]:
array[array % 2 == 0]

array([500,  10,  40,  30, 310,  20,  30,  30])

In [69]:
array[(array % 2 == 0) & (array > 50)]

array([500, 310])

In [ ]:
array = np.array([23, 41, 500, 10, 40, 30, 310, 20, 30, 101, 203, 30])
array

In [74]:
array[(array % 3 == 0) | (array < 40)] 

array([23, 10, 30, 20, 30, 30])